version: '3'
services:
  api:
    build: ./api/
    depends_on:
      - elasticsearch
    environment:
      - GRPC_PORT=50051
      - HTTP_PORT=8080
      - ELASTICSEARCH_URL=elasticsearch:9200
    ports:
      - 8080:8080

  scraper:
    build: ./scraper/
    depends_on: 
      - api
    environment: 
      - API_URL=api:8080

  elasticsearch:
    build: ./elasticsearch
    volumes:
      - ./elasticsearch/data:/usr/share/elasticsearch/data
      - ./elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - 9200:9200

  kibana:
    image: kibana
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
