version: '3'
services:
  api:
    build: ./api/
    depends_on:
      - elasticsearch
    ports:
      - 8080:8080

  # scraper:
  #   build: ./scraper/

  elasticsearch:
    image: elasticsearch

  kibana:
    image: kibana
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
