apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: personal-site-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: personal-site-api
    spec:
      containers:
      - name: personal-site
        image: gcr.io/personal-200804/site-dev:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
            limits:
              cpu: 1
            requests:
              cpu: 10m
        env:
        - name: API_URL
          value: "http://localhost:8001/api/v1/namespaces/default/services/personal-api-service/proxy/"
      imagePullSecrets:
      - name: gcr
---
kind: Service
apiVersion: v1
metadata:
  name: personal-site-service
spec:
  selector:
    app: personal-site-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: personal-api-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: personal-site-api
    spec:
      containers:
      - name: personal-api
        image: gcr.io/personal-200804/api-dev:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
        resources:
            limits:
              cpu: 1
            requests:
              cpu: 10m
      imagePullSecrets:
        - name: gcr
---
kind: Service
apiVersion: v1
metadata:
  name: personal-api-service
spec:
  selector:
    app: personal-site-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
  type: LoadBalancer