// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/movie.proto

package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type PostMoviesPayload struct {
	Movies []*PostMoviesPayload_Movie `protobuf:"bytes,1,rep,name=movies" json:"movies,omitempty"`
}

func (m *PostMoviesPayload) Reset()                    { *m = PostMoviesPayload{} }
func (m *PostMoviesPayload) String() string            { return proto1.CompactTextString(m) }
func (*PostMoviesPayload) ProtoMessage()               {}
func (*PostMoviesPayload) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *PostMoviesPayload) GetMovies() []*PostMoviesPayload_Movie {
	if m != nil {
		return m.Movies
	}
	return nil
}

type PostMoviesPayload_IMDBMeta struct {
	Genre      string  `protobuf:"bytes,1,opt,name=genre" json:"genre,omitempty"`
	MpaaRating string  `protobuf:"bytes,2,opt,name=mpaa_rating,json=mpaaRating" json:"mpaa_rating,omitempty"`
	Score      float32 `protobuf:"fixed32,3,opt,name=score" json:"score,omitempty"`
}

func (m *PostMoviesPayload_IMDBMeta) Reset()                    { *m = PostMoviesPayload_IMDBMeta{} }
func (m *PostMoviesPayload_IMDBMeta) String() string            { return proto1.CompactTextString(m) }
func (*PostMoviesPayload_IMDBMeta) ProtoMessage()               {}
func (*PostMoviesPayload_IMDBMeta) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0, 0} }

func (m *PostMoviesPayload_IMDBMeta) GetGenre() string {
	if m != nil {
		return m.Genre
	}
	return ""
}

func (m *PostMoviesPayload_IMDBMeta) GetMpaaRating() string {
	if m != nil {
		return m.MpaaRating
	}
	return ""
}

func (m *PostMoviesPayload_IMDBMeta) GetScore() float32 {
	if m != nil {
		return m.Score
	}
	return 0
}

type PostMoviesPayload_RottenTomatoesMeta struct {
	TomatoScore        int64  `protobuf:"varint,1,opt,name=tomato_score,json=tomatoScore" json:"tomato_score,omitempty"`
	PopcornScore       int64  `protobuf:"varint,2,opt,name=popcorn_score,json=popcornScore" json:"popcorn_score,omitempty"`
	TheaterReleaseDate string `protobuf:"bytes,3,opt,name=theater_release_date,json=theaterReleaseDate" json:"theater_release_date,omitempty"`
	MpaaRating         string `protobuf:"bytes,4,opt,name=mpaa_rating,json=mpaaRating" json:"mpaa_rating,omitempty"`
	Synopsis           string `protobuf:"bytes,5,opt,name=synopsis" json:"synopsis,omitempty"`
	SynopsisType       string `protobuf:"bytes,6,opt,name=synopsis_type,json=synopsisType" json:"synopsis_type,omitempty"`
	Runtime            string `protobuf:"bytes,7,opt,name=runtime" json:"runtime,omitempty"`
}

func (m *PostMoviesPayload_RottenTomatoesMeta) Reset()         { *m = PostMoviesPayload_RottenTomatoesMeta{} }
func (m *PostMoviesPayload_RottenTomatoesMeta) String() string { return proto1.CompactTextString(m) }
func (*PostMoviesPayload_RottenTomatoesMeta) ProtoMessage()    {}
func (*PostMoviesPayload_RottenTomatoesMeta) Descriptor() ([]byte, []int) {
	return fileDescriptor1, []int{0, 1}
}

func (m *PostMoviesPayload_RottenTomatoesMeta) GetTomatoScore() int64 {
	if m != nil {
		return m.TomatoScore
	}
	return 0
}

func (m *PostMoviesPayload_RottenTomatoesMeta) GetPopcornScore() int64 {
	if m != nil {
		return m.PopcornScore
	}
	return 0
}

func (m *PostMoviesPayload_RottenTomatoesMeta) GetTheaterReleaseDate() string {
	if m != nil {
		return m.TheaterReleaseDate
	}
	return ""
}

func (m *PostMoviesPayload_RottenTomatoesMeta) GetMpaaRating() string {
	if m != nil {
		return m.MpaaRating
	}
	return ""
}

func (m *PostMoviesPayload_RottenTomatoesMeta) GetSynopsis() string {
	if m != nil {
		return m.Synopsis
	}
	return ""
}

func (m *PostMoviesPayload_RottenTomatoesMeta) GetSynopsisType() string {
	if m != nil {
		return m.SynopsisType
	}
	return ""
}

func (m *PostMoviesPayload_RottenTomatoesMeta) GetRuntime() string {
	if m != nil {
		return m.Runtime
	}
	return ""
}

type PostMoviesPayload_Movie struct {
	Title              string                                `protobuf:"bytes,1,opt,name=title" json:"title,omitempty"`
	ImdbMeta           *PostMoviesPayload_IMDBMeta           `protobuf:"bytes,2,opt,name=imdb_meta,json=imdbMeta" json:"imdb_meta,omitempty"`
	RottenTomatoesMeta *PostMoviesPayload_RottenTomatoesMeta `protobuf:"bytes,3,opt,name=rotten_tomatoes_meta,json=rottenTomatoesMeta" json:"rotten_tomatoes_meta,omitempty"`
}

func (m *PostMoviesPayload_Movie) Reset()                    { *m = PostMoviesPayload_Movie{} }
func (m *PostMoviesPayload_Movie) String() string            { return proto1.CompactTextString(m) }
func (*PostMoviesPayload_Movie) ProtoMessage()               {}
func (*PostMoviesPayload_Movie) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0, 2} }

func (m *PostMoviesPayload_Movie) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *PostMoviesPayload_Movie) GetImdbMeta() *PostMoviesPayload_IMDBMeta {
	if m != nil {
		return m.ImdbMeta
	}
	return nil
}

func (m *PostMoviesPayload_Movie) GetRottenTomatoesMeta() *PostMoviesPayload_RottenTomatoesMeta {
	if m != nil {
		return m.RottenTomatoesMeta
	}
	return nil
}

type PostMoviesResponse struct {
	Success bool `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
}

func (m *PostMoviesResponse) Reset()                    { *m = PostMoviesResponse{} }
func (m *PostMoviesResponse) String() string            { return proto1.CompactTextString(m) }
func (*PostMoviesResponse) ProtoMessage()               {}
func (*PostMoviesResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *PostMoviesResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func init() {
	proto1.RegisterType((*PostMoviesPayload)(nil), "proto.PostMoviesPayload")
	proto1.RegisterType((*PostMoviesPayload_IMDBMeta)(nil), "proto.PostMoviesPayload.IMDBMeta")
	proto1.RegisterType((*PostMoviesPayload_RottenTomatoesMeta)(nil), "proto.PostMoviesPayload.RottenTomatoesMeta")
	proto1.RegisterType((*PostMoviesPayload_Movie)(nil), "proto.PostMoviesPayload.Movie")
	proto1.RegisterType((*PostMoviesResponse)(nil), "proto.PostMoviesResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for MovieService service

type MovieServiceClient interface {
	Post(ctx context.Context, in *PostMoviesPayload, opts ...grpc.CallOption) (*PostMoviesResponse, error)
}

type movieServiceClient struct {
	cc *grpc.ClientConn
}

func NewMovieServiceClient(cc *grpc.ClientConn) MovieServiceClient {
	return &movieServiceClient{cc}
}

func (c *movieServiceClient) Post(ctx context.Context, in *PostMoviesPayload, opts ...grpc.CallOption) (*PostMoviesResponse, error) {
	out := new(PostMoviesResponse)
	err := grpc.Invoke(ctx, "/proto.MovieService/Post", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for MovieService service

type MovieServiceServer interface {
	Post(context.Context, *PostMoviesPayload) (*PostMoviesResponse, error)
}

func RegisterMovieServiceServer(s *grpc.Server, srv MovieServiceServer) {
	s.RegisterService(&_MovieService_serviceDesc, srv)
}

func _MovieService_Post_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostMoviesPayload)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MovieServiceServer).Post(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.MovieService/Post",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MovieServiceServer).Post(ctx, req.(*PostMoviesPayload))
	}
	return interceptor(ctx, in, info, handler)
}

var _MovieService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.MovieService",
	HandlerType: (*MovieServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Post",
			Handler:    _MovieService_Post_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/movie.proto",
}

func init() { proto1.RegisterFile("proto/movie.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 452 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x53, 0xbd, 0x8e, 0xd3, 0x40,
	0x10, 0x96, 0xf3, 0x9f, 0x89, 0x29, 0x6e, 0x95, 0xc2, 0x58, 0x08, 0x72, 0xa1, 0x89, 0x40, 0x4a,
	0x50, 0x90, 0x28, 0x28, 0x28, 0xd0, 0x35, 0x14, 0x11, 0xa7, 0xbd, 0x93, 0xa8, 0x90, 0xb5, 0xe7,
	0x8c, 0x82, 0xa5, 0x78, 0x77, 0xb5, 0x3b, 0x77, 0x52, 0x5a, 0x4a, 0x5a, 0x5e, 0x87, 0xb7, 0xe0,
	0x15, 0x78, 0x00, 0x1e, 0x01, 0xed, 0xac, 0x7d, 0x14, 0x56, 0x2a, 0xef, 0xf7, 0xcd, 0xf7, 0xcd,
	0xee, 0x7c, 0x23, 0xc3, 0x85, 0x75, 0x86, 0xcc, 0xa6, 0x36, 0x0f, 0x15, 0xae, 0xf9, 0x2c, 0x86,
	0xfc, 0xc9, 0x9f, 0x1d, 0x8c, 0x39, 0x1c, 0x71, 0xa3, 0x6c, 0xb5, 0x51, 0x5a, 0x1b, 0x52, 0x54,
	0x19, 0xed, 0xa3, 0x68, 0xf9, 0x77, 0x00, 0x17, 0xd7, 0xc6, 0xd3, 0x2e, 0x18, 0xfd, 0xb5, 0x3a,
	0x1d, 0x8d, 0xda, 0x8b, 0x77, 0x30, 0xe2, 0x4e, 0x3e, 0x4b, 0x16, 0xfd, 0xd5, 0x6c, 0xfb, 0x3c,
	0xaa, 0xd7, 0x1d, 0xe5, 0x9a, 0x91, 0x6c, 0xd4, 0xf9, 0x17, 0x98, 0x7c, 0xda, 0x5d, 0x7d, 0xdc,
	0x21, 0x29, 0x31, 0x87, 0xe1, 0x01, 0xb5, 0xc3, 0x2c, 0x59, 0x24, 0xab, 0xa9, 0x8c, 0x40, 0xbc,
	0x80, 0x59, 0x6d, 0x95, 0x2a, 0x9c, 0xa2, 0x4a, 0x1f, 0xb2, 0x1e, 0xd7, 0x20, 0x50, 0x92, 0x99,
	0x60, 0xf3, 0xa5, 0x71, 0x98, 0xf5, 0x17, 0xc9, 0xaa, 0x27, 0x23, 0xc8, 0x7f, 0xf4, 0x40, 0x48,
	0x43, 0x84, 0xfa, 0xd6, 0xd4, 0x8a, 0x0c, 0x7a, 0xbe, 0xe3, 0x12, 0x52, 0x62, 0x5c, 0x44, 0x4f,
	0xb8, 0xaa, 0x2f, 0x67, 0x91, 0xbb, 0x09, 0x94, 0x78, 0x09, 0x4f, 0xac, 0xb1, 0xa5, 0x71, 0xba,
	0xd1, 0xf4, 0x58, 0x93, 0x36, 0x64, 0x14, 0xbd, 0x81, 0x39, 0x7d, 0x43, 0x45, 0xe8, 0x0a, 0x87,
	0x47, 0x54, 0x1e, 0x8b, 0xbd, 0xa2, 0xf8, 0x86, 0xa9, 0x14, 0x4d, 0x4d, 0xc6, 0xd2, 0x95, 0xa2,
	0xce, 0x1c, 0x83, 0xce, 0x1c, 0x39, 0x4c, 0xfc, 0x49, 0x1b, 0xeb, 0x2b, 0x9f, 0x0d, 0xb9, 0xfa,
	0x88, 0xc3, 0x9b, 0xda, 0x73, 0x41, 0x27, 0x8b, 0xd9, 0x88, 0x05, 0x69, 0x4b, 0xde, 0x9e, 0x2c,
	0x8a, 0x0c, 0xc6, 0xee, 0x5e, 0x53, 0x55, 0x63, 0x36, 0xe6, 0x72, 0x0b, 0xf3, 0x5f, 0x09, 0x0c,
	0x39, 0xf7, 0x10, 0x16, 0x55, 0x74, 0x7c, 0xcc, 0x98, 0x81, 0xf8, 0x00, 0xd3, 0xaa, 0xde, 0xdf,
	0x15, 0x35, 0x92, 0xe2, 0x71, 0x67, 0xdb, 0xcb, 0xb3, 0x0b, 0x6c, 0xf7, 0x25, 0x27, 0xc1, 0xc3,
	0xa9, 0x7e, 0x85, 0xb9, 0xe3, 0xac, 0x0b, 0x6a, 0xc2, 0x8e, 0xad, 0xfa, 0xdc, 0xea, 0xf5, 0xd9,
	0x56, 0xdd, 0x05, 0x49, 0xe1, 0x3a, 0xdc, 0x72, 0x0d, 0xe2, 0xbf, 0x57, 0xa2, 0xb7, 0x46, 0x7b,
	0x1e, 0xd7, 0xdf, 0x97, 0x25, 0x7a, 0xcf, 0xc3, 0x4c, 0x64, 0x0b, 0xb7, 0x05, 0xa4, 0xac, 0xbd,
	0x41, 0xf7, 0x50, 0x95, 0x28, 0x3e, 0xc3, 0x20, 0xf8, 0x45, 0x76, 0xee, 0x21, 0xf9, 0xd3, 0x4e,
	0xa5, 0xbd, 0x66, 0x29, 0xbe, 0xff, 0xfe, 0xf3, 0xb3, 0x97, 0x2e, 0xc7, 0xf1, 0x57, 0xf1, 0xef,
	0x93, 0x57, 0x77, 0x23, 0x56, 0xbf, 0xfd, 0x17, 0x00, 0x00, 0xff, 0xff, 0xfb, 0xb5, 0xcc, 0xac,
	0x44, 0x03, 0x00, 0x00,
}
