// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/resume.proto

package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"
import google_protobuf1 "github.com/golang/protobuf/ptypes/empty"
import google_protobuf2 "github.com/golang/protobuf/ptypes/timestamp"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type ResumeResponse struct {
	FirstName  string                       `protobuf:"bytes,1,opt,name=first_name,json=firstName" json:"first_name,omitempty"`
	LastName   string                       `protobuf:"bytes,2,opt,name=last_name,json=lastName" json:"last_name,omitempty"`
	Headline   string                       `protobuf:"bytes,3,opt,name=headline" json:"headline,omitempty"`
	Summary    string                       `protobuf:"bytes,4,opt,name=summary" json:"summary,omitempty"`
	Experience []*ResumeResponse_Experience `protobuf:"bytes,5,rep,name=experience" json:"experience,omitempty"`
}

func (m *ResumeResponse) Reset()                    { *m = ResumeResponse{} }
func (m *ResumeResponse) String() string            { return proto1.CompactTextString(m) }
func (*ResumeResponse) ProtoMessage()               {}
func (*ResumeResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *ResumeResponse) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *ResumeResponse) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *ResumeResponse) GetHeadline() string {
	if m != nil {
		return m.Headline
	}
	return ""
}

func (m *ResumeResponse) GetSummary() string {
	if m != nil {
		return m.Summary
	}
	return ""
}

func (m *ResumeResponse) GetExperience() []*ResumeResponse_Experience {
	if m != nil {
		return m.Experience
	}
	return nil
}

type ResumeResponse_DateRange struct {
	Start   *google_protobuf2.Timestamp `protobuf:"bytes,1,opt,name=start" json:"start,omitempty"`
	End     *google_protobuf2.Timestamp `protobuf:"bytes,2,opt,name=end" json:"end,omitempty"`
	Display string                      `protobuf:"bytes,3,opt,name=display" json:"display,omitempty"`
}

func (m *ResumeResponse_DateRange) Reset()                    { *m = ResumeResponse_DateRange{} }
func (m *ResumeResponse_DateRange) String() string            { return proto1.CompactTextString(m) }
func (*ResumeResponse_DateRange) ProtoMessage()               {}
func (*ResumeResponse_DateRange) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0, 0} }

func (m *ResumeResponse_DateRange) GetStart() *google_protobuf2.Timestamp {
	if m != nil {
		return m.Start
	}
	return nil
}

func (m *ResumeResponse_DateRange) GetEnd() *google_protobuf2.Timestamp {
	if m != nil {
		return m.End
	}
	return nil
}

func (m *ResumeResponse_DateRange) GetDisplay() string {
	if m != nil {
		return m.Display
	}
	return ""
}

type ResumeResponse_Experience struct {
	Title       string                    `protobuf:"bytes,1,opt,name=title" json:"title,omitempty"`
	Company     string                    `protobuf:"bytes,2,opt,name=company" json:"company,omitempty"`
	Location    string                    `protobuf:"bytes,3,opt,name=location" json:"location,omitempty"`
	Description string                    `protobuf:"bytes,4,opt,name=description" json:"description,omitempty"`
	DateRange   *ResumeResponse_DateRange `protobuf:"bytes,5,opt,name=date_range,json=dateRange" json:"date_range,omitempty"`
}

func (m *ResumeResponse_Experience) Reset()                    { *m = ResumeResponse_Experience{} }
func (m *ResumeResponse_Experience) String() string            { return proto1.CompactTextString(m) }
func (*ResumeResponse_Experience) ProtoMessage()               {}
func (*ResumeResponse_Experience) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0, 1} }

func (m *ResumeResponse_Experience) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *ResumeResponse_Experience) GetCompany() string {
	if m != nil {
		return m.Company
	}
	return ""
}

func (m *ResumeResponse_Experience) GetLocation() string {
	if m != nil {
		return m.Location
	}
	return ""
}

func (m *ResumeResponse_Experience) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *ResumeResponse_Experience) GetDateRange() *ResumeResponse_DateRange {
	if m != nil {
		return m.DateRange
	}
	return nil
}

type ResumeResponse_Education struct {
	Degree    string                    `protobuf:"bytes,1,opt,name=degree" json:"degree,omitempty"`
	Major     string                    `protobuf:"bytes,2,opt,name=major" json:"major,omitempty"`
	School    string                    `protobuf:"bytes,3,opt,name=school" json:"school,omitempty"`
	Location  string                    `protobuf:"bytes,4,opt,name=location" json:"location,omitempty"`
	DateRange *ResumeResponse_DateRange `protobuf:"bytes,5,opt,name=date_range,json=dateRange" json:"date_range,omitempty"`
}

func (m *ResumeResponse_Education) Reset()                    { *m = ResumeResponse_Education{} }
func (m *ResumeResponse_Education) String() string            { return proto1.CompactTextString(m) }
func (*ResumeResponse_Education) ProtoMessage()               {}
func (*ResumeResponse_Education) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0, 2} }

func (m *ResumeResponse_Education) GetDegree() string {
	if m != nil {
		return m.Degree
	}
	return ""
}

func (m *ResumeResponse_Education) GetMajor() string {
	if m != nil {
		return m.Major
	}
	return ""
}

func (m *ResumeResponse_Education) GetSchool() string {
	if m != nil {
		return m.School
	}
	return ""
}

func (m *ResumeResponse_Education) GetLocation() string {
	if m != nil {
		return m.Location
	}
	return ""
}

func (m *ResumeResponse_Education) GetDateRange() *ResumeResponse_DateRange {
	if m != nil {
		return m.DateRange
	}
	return nil
}

func init() {
	proto1.RegisterType((*ResumeResponse)(nil), "proto.ResumeResponse")
	proto1.RegisterType((*ResumeResponse_DateRange)(nil), "proto.ResumeResponse.DateRange")
	proto1.RegisterType((*ResumeResponse_Experience)(nil), "proto.ResumeResponse.Experience")
	proto1.RegisterType((*ResumeResponse_Education)(nil), "proto.ResumeResponse.Education")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for ResumeService service

type ResumeServiceClient interface {
	Get(ctx context.Context, in *google_protobuf1.Empty, opts ...grpc.CallOption) (*ResumeResponse, error)
}

type resumeServiceClient struct {
	cc *grpc.ClientConn
}

func NewResumeServiceClient(cc *grpc.ClientConn) ResumeServiceClient {
	return &resumeServiceClient{cc}
}

func (c *resumeServiceClient) Get(ctx context.Context, in *google_protobuf1.Empty, opts ...grpc.CallOption) (*ResumeResponse, error) {
	out := new(ResumeResponse)
	err := grpc.Invoke(ctx, "/proto.ResumeService/Get", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ResumeService service

type ResumeServiceServer interface {
	Get(context.Context, *google_protobuf1.Empty) (*ResumeResponse, error)
}

func RegisterResumeServiceServer(s *grpc.Server, srv ResumeServiceServer) {
	s.RegisterService(&_ResumeService_serviceDesc, srv)
}

func _ResumeService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(google_protobuf1.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResumeServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ResumeService/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResumeServiceServer).Get(ctx, req.(*google_protobuf1.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _ResumeService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.ResumeService",
	HandlerType: (*ResumeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _ResumeService_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/resume.proto",
}

func init() { proto1.RegisterFile("proto/resume.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 451 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x53, 0x4d, 0x6e, 0xd4, 0x30,
	0x18, 0x55, 0x3a, 0x4d, 0x69, 0xbe, 0x01, 0x16, 0x16, 0x54, 0x51, 0x0a, 0xea, 0xa8, 0xab, 0x2e,
	0x50, 0x02, 0xc3, 0x1e, 0xb1, 0x60, 0x04, 0x2b, 0x16, 0x81, 0x0d, 0xab, 0xca, 0x8d, 0xbf, 0x4e,
	0x8d, 0xe2, 0x1f, 0xd9, 0x9e, 0x8a, 0x6c, 0x91, 0x38, 0x01, 0xe7, 0xe0, 0x00, 0x70, 0x0d, 0xae,
	0xc0, 0x41, 0x90, 0xff, 0x4a, 0x5b, 0x46, 0x6c, 0x58, 0x25, 0xef, 0x7b, 0xcf, 0xf6, 0x7b, 0xcf,
	0x32, 0x10, 0x6d, 0x94, 0x53, 0x9d, 0x41, 0xbb, 0x11, 0xd8, 0x06, 0x40, 0xca, 0xf0, 0x69, 0x1e,
	0xad, 0x95, 0x5a, 0x8f, 0xd8, 0x51, 0xcd, 0x3b, 0x2a, 0xa5, 0x72, 0xd4, 0x71, 0x25, 0x6d, 0x14,
	0x35, 0x87, 0x89, 0x0d, 0xe8, 0x6c, 0x73, 0xde, 0xa1, 0xd0, 0x6e, 0x4a, 0xe4, 0xd1, 0x6d, 0xd2,
	0x71, 0x81, 0xd6, 0x51, 0xa1, 0xa3, 0xe0, 0xf8, 0x7b, 0x09, 0xf7, 0xfb, 0x70, 0x66, 0x8f, 0x56,
	0x2b, 0x69, 0x91, 0x3c, 0x06, 0x38, 0xe7, 0xc6, 0xba, 0x53, 0x49, 0x05, 0xd6, 0xc5, 0xa2, 0x38,
	0xa9, 0xfa, 0x2a, 0x4c, 0xde, 0x52, 0x81, 0xe4, 0x10, 0xaa, 0x91, 0x66, 0x76, 0x27, 0xb0, 0xfb,
	0x7e, 0x10, 0xc8, 0x06, 0xf6, 0x2f, 0x90, 0xb2, 0x91, 0x4b, 0xac, 0x67, 0x91, 0xcb, 0x98, 0xd4,
	0x70, 0xc7, 0x6e, 0x84, 0xa0, 0x66, 0xaa, 0x77, 0x03, 0x95, 0x21, 0x79, 0x09, 0x80, 0x9f, 0x34,
	0x1a, 0x8e, 0x72, 0xc0, 0xba, 0x5c, 0xcc, 0x4e, 0xe6, 0xcb, 0x45, 0x34, 0xd8, 0xde, 0x34, 0xd7,
	0xae, 0xae, 0x74, 0xfd, 0xb5, 0x35, 0xcd, 0x97, 0x02, 0xaa, 0x57, 0xd4, 0x61, 0x4f, 0xe5, 0x1a,
	0xc9, 0x53, 0x28, 0xad, 0xa3, 0xc6, 0x05, 0xf3, 0xf3, 0x65, 0xd3, 0xc6, 0x16, 0xda, 0xdc, 0x42,
	0xfb, 0x3e, 0xb7, 0xd0, 0x47, 0x21, 0x79, 0x02, 0x33, 0x94, 0x2c, 0xc4, 0xf9, 0xb7, 0xde, 0xcb,
	0x7c, 0x12, 0xc6, 0xad, 0x1e, 0xe9, 0x94, 0x42, 0x66, 0xd8, 0xfc, 0x28, 0x00, 0xfe, 0x58, 0x24,
	0x0f, 0xa0, 0x74, 0xdc, 0x8d, 0xb9, 0xc5, 0x08, 0xfc, 0xf2, 0x41, 0x09, 0x4d, 0xe5, 0x94, 0xfa,
	0xcb, 0xd0, 0xd7, 0x37, 0xaa, 0x21, 0x5c, 0x6f, 0xae, 0x2f, 0x63, 0xb2, 0x80, 0x39, 0x43, 0x3b,
	0x18, 0xae, 0x03, 0x1d, 0x2b, 0xbc, 0x3e, 0x22, 0x2f, 0x00, 0x18, 0x75, 0x78, 0x6a, 0x7c, 0x09,
	0x75, 0x19, 0xb2, 0x1c, 0x6d, 0xaf, 0xf1, 0xaa, 0xab, 0xbe, 0x62, 0xf9, 0xb7, 0xf9, 0x56, 0x40,
	0xb5, 0x62, 0x9b, 0x74, 0xde, 0x01, 0xec, 0x31, 0x5c, 0x1b, 0xcc, 0xe6, 0x13, 0xf2, 0x99, 0x04,
	0xfd, 0xa8, 0x4c, 0xf2, 0x1e, 0x81, 0x57, 0xdb, 0xe1, 0x42, 0xa9, 0x31, 0xf9, 0x4e, 0xe8, 0x46,
	0xa2, 0xdd, 0x5b, 0x89, 0xfe, 0xd3, 0xef, 0xf2, 0x03, 0xdc, 0x8b, 0xb2, 0x77, 0x68, 0x2e, 0xf9,
	0x80, 0xe4, 0x0d, 0xcc, 0x5e, 0xa3, 0x23, 0x07, 0x7f, 0xdd, 0xdf, 0xca, 0x3f, 0x89, 0xe6, 0xe1,
	0xd6, 0xbd, 0x8f, 0xc9, 0xe7, 0x9f, 0xbf, 0xbe, 0xee, 0xdc, 0x25, 0xd0, 0x5d, 0x3e, 0x4b, 0xef,
	0xef, 0x6c, 0x2f, 0x28, 0x9f, 0xff, 0x0e, 0x00, 0x00, 0xff, 0xff, 0x42, 0x06, 0x68, 0x17, 0x96,
	0x03, 0x00, 0x00,
}
